
import { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

const translations = {
  en: {
    name: 'English',
    flag: '🇬🇧',
    nav: {
      home: 'Home',
      registerWithCode: 'Register with Code',
      hospitalDashboard: 'Hospital Dashboard',
      organDonation: 'Organ Donation',
      leaderboard: 'Leaderboard',
      inventory: 'Blood Bank',
      predictions: 'Predictions',
      cooldown: 'Cooldown Tracker',
    },
    home: {
      heroTitle: 'Connecting Donors.',
      heroTitle2: 'Saving Lives.',
      heroSubtitle: 'Real-time blood donation matching across Africa. Every drop counts.',
      registerBtn: 'Register as Donor',
      hospitalBtn: 'Hospital Login',
      realTimeMatching: 'Real-Time Matching',
      realTimeDesc: 'Instantly connects compatible donors with urgent requests based on blood type and location',
      urgencyTiers: 'Urgency Tiers',
      urgencyDesc: 'Critical, High, and Standard tiers ensure the most urgent cases get priority attention',
      verifiedDonors: 'Verified Donors Only',
      verifiedDesc: 'Every donor is medically screened and verified at a hospital before joining the platform',
      howItWorks: 'How It Works',
      step1Title: 'Visit Hospital',
      step1Desc: 'Go to a participating hospital for a free blood screening',
      step2Title: 'Get Screened',
      step2Desc: 'Blood type test, BMI check, and health eligibility assessment',
      step3Title: 'Receive Code',
      step3Desc: 'Once cleared, get your unique LifeLink registration code',
      step4Title: 'Register Online',
      step4Desc: 'Enter your code on LifeLink to activate your donor account',
      statHeadline: 'Every 2 seconds, someone needs blood.',
      statSubtext: 'In Africa, the gap between supply and demand is deadly and preventable. LifeLink removes the friction.',
      footer: 'LifeLink 2026 — Built with AWS Serverless Architecture',
    },
    donor: {
      enterCode: 'Enter Your Registration Code',
      codeSubtitle: 'You received this code from the hospital after your medical screening.',
      registrationCode: 'Registration Code',
      verifyCode: 'Verify Code',
      noCode: "Don't have a code?",
      noCodeDesc: "Visit your nearest participating hospital for a free blood donation screening. Once cleared, you'll receive a registration code.",
      codeVerified: 'Code Verified Successfully',
      contactDetails: 'Contact Details',
      phone: 'Phone Number',
      email: 'Email',
      address: 'Address',
      city: 'City',
      province: 'Province',
      notificationPrefs: 'Notification Preferences',
      howNotify: 'How should we notify you?',
      smsOnly: 'SMS Only',
      emailOnly: 'Email Only',
      both: 'Both',
      maxDistance: 'Maximum Distance Willing to Travel',
      emergencyContact: 'Emergency Contact',
      contactName: 'Contact Name',
      contactPhone: 'Contact Phone',
      completeRegistration: 'Complete Registration',
      welcomeTitle: 'Welcome to LifeLink!',
      welcomeSubtitle: "Your account is now active. You'll be notified when a compatible patient needs you nearby.",
      whatNext: 'What happens next?',
      next1: 'Go about your day as normal',
      next2: "When a compatible patient needs blood near you, you'll get a notification",
      next3: 'Tap "I\'ll donate" to confirm, then head to the hospital',
      next4: 'Your next eligible donation date will be tracked automatically (56-day cooldown)',
      goHome: 'Go Home',
      viewDemo: 'View Demo Notification',
    },
    notification: {
      hospitalNeeds: 'needs',
      blood: 'blood',
      urgency: 'Urgency',
      distance: 'Distance',
      fromYou: 'from you',
      illDonate: "I'll Donate",
      cantMakeIt: "Can't Make It",
    },
    common: {
      bloodType: 'Blood Type',
      units: 'units',
      status: 'Status',
      active: 'Active',
      eligible: 'Eligible',
      critical: 'Critical',
      high: 'High',
      standard: 'Standard',
      search: 'Search',
      filter: 'Filter',
      cancel: 'Cancel',
      submit: 'Submit',
      save: 'Save',
      back: 'Back',
      next: 'Next',
      loading: 'Loading...',
      noResults: 'No results found',
    },
  },
  zu: {
    name: 'isiZulu',
    flag: '🇿🇦',
    nav: {
      home: 'Ikhaya',
      registerWithCode: 'Bhalisa ngeKhodi',
      hospitalDashboard: 'Idashbhodi Yesibhedlela',
      organDonation: 'Ukunikela Ngezitho',
      leaderboard: 'Ibhodi Labaholi',
      inventory: 'Ibhange Legazi',
      predictions: 'Izibikezelo',
      cooldown: 'Isikhathi Sokuphumula',
    },
    home: {
      heroTitle: 'Sixhumanisa Abanikeli.',
      heroTitle2: 'Sisindisa Izimpilo.',
      heroSubtitle: 'Ukuxhumanisa ukunikela ngegazi ngesikhathi sangempela e-Afrika. Lonke iconsi libalulekile.',
      registerBtn: 'Bhalisa Njengomnikeli',
      hospitalBtn: 'Ngena Esibhedlela',
      realTimeMatching: 'Ukuxhumanisa Ngesikhathi Sangempela',
      realTimeDesc: 'Ixhumanisa ngokushesha abanikeli abahambisanayo nezicelo eziphuthumayo ngohlobo lwegazi nendawo',
      urgencyTiers: 'Amazinga Okushesha',
      urgencyDesc: 'Amazinga eCritical, High, neStandard aqinisekisa ukuthi izimo eziphuthumayo kakhulu zithola ukunakwa kuqala',
      verifiedDonors: 'Abanikeli Abaqinisekisiwe Kuphela',
      verifiedDesc: 'Wonke umnikeli uhlolwa ngokwezokwelapha futhi uqinisekiswa esibhedlela ngaphambi kokujoyina inkundla',
      howItWorks: 'Kusebenza Kanjani',
      step1Title: 'Vakashela Isibhedlela',
      step1Desc: 'Yana esibhedlela esibambe iqhaza ukuze uhlolwe igazi mahhala',
      step2Title: 'Hlolwa',
      step2Desc: 'Ukuhlolwa kohlobo lwegazi, ukuhlolwa kwe-BMI, nokuhlolwa kokufaneleka kwempilo',
      step3Title: 'Thola Ikhodi',
      step3Desc: 'Uma usuvunyelwe, thola ikhodi yakho ekhethekile yokubhalisa ku-LifeLink',
      step4Title: 'Bhalisa Ku-inthanethi',
      step4Desc: 'Faka ikhodi yakho ku-LifeLink ukuze uvule i-akhawunti yakho yomnikeli',
      statHeadline: 'Njalo ngemizuzwana engu-2, kukhona odinga igazi.',
      statSubtext: 'E-Afrika, igebe phakathi kokuhlinzekwa nesidingo liyabulala futhi linganqandeka. I-LifeLink isusa izithiyo.',
      footer: 'LifeLink 2026 — Yakhiwe nge-AWS Serverless Architecture',
    },
    donor: {
      enterCode: 'Faka Ikhodi Yakho Yokubhalisa',
      codeSubtitle: 'Uthole le khodi esibhedlela ngemva kokuhlolwa kwakho kwezokwelapha.',
      registrationCode: 'Ikhodi Yokubhalisa',
      verifyCode: 'Qinisekisa Ikhodi',
      noCode: 'Awunayo ikhodi?',
      noCodeDesc: 'Vakashela isibhedlela sakho esiseduze esibambe iqhaza ukuze uhlolwe ukunikela ngegazi mahhala. Uma usuvunyelwe, uzothola ikhodi yokubhalisa.',
      codeVerified: 'Ikhodi Iqinisekisiwe Ngempumelelo',
      contactDetails: 'Imininingwane Yokuxhumana',
      phone: 'Inombolo Yocingo',
      email: 'I-imeyili',
      address: 'Ikheli',
      city: 'Idolobha',
      province: 'Isifundazwe',
      notificationPrefs: 'Izintandokazi Zezaziso',
      howNotify: 'Kufanele sikwazise kanjani?',
      smsOnly: 'I-SMS Kuphela',
      emailOnly: 'I-imeyili Kuphela',
      both: 'Kokubili',
      maxDistance: 'Ibanga Elide Kakhulu Ozimisele Ukulihamba',
      emergencyContact: 'Oxhumana Naye Ngesikhathi Esiphuthumayo',
      contactName: 'Igama Loxhumana Naye',
      contactPhone: 'Ucingo Loxhumana Naye',
      completeRegistration: 'Qedela Ukubhalisa',
      welcomeTitle: 'Siyakwamukela ku-LifeLink!',
      welcomeSubtitle: 'I-akhawunti yakho isebenza manje. Uzokwaziswa uma isiguli esihambisanayo sikudinga eduze.',
      whatNext: 'Kwenzekani ngokulandelayo?',
      next1: 'Qhubeka nosuku lwakho njengokuvamile',
      next2: 'Uma isiguli esihambisanayo sidinga igazi eduze nawe, uzothola isaziso',
      next3: 'Thepha "Ngizonikela" ukuqinisekisa, bese uya esibhedlela',
      next4: 'Usuku lwakho olulandelayo lokufaneleka luzolandelwa ngokuzenzakalelayo (izinsuku ezingu-56 zokuphumula)',
      goHome: 'Yana Ekhaya',
      viewDemo: 'Buka Isaziso Sedemo',
    },
    notification: {
      hospitalNeeds: 'idinga',
      blood: 'igazi',
      urgency: 'Ukushesha',
      distance: 'Ibanga',
      fromYou: 'ukusuka kuwe',
      illDonate: 'Ngizonikela',
      cantMakeIt: 'Angikwazi',
    },
    common: {
      bloodType: 'Uhlobo Lwegazi',
      units: 'amayunithi',
      status: 'Isimo',
      active: 'Kuyasebenza',
      eligible: 'Kuyafaneleka',
      critical: 'Kuphuthumile',
      high: 'Kuphezulu',
      standard: 'Okujwayelekile',
      search: 'Sesha',
      filter: 'Hlunga',
      cancel: 'Khansela',
      submit: 'Thumela',
      save: 'Gcina',
      back: 'Emuva',
      next: 'Okulandelayo',
      loading: 'Iyalayisha...',
      noResults: 'Ayikho imiphumela etholakele',
    },
  },
  xh: {
    name: 'isiXhosa',
    flag: '🇿🇦',
    nav: {
      home: 'Ikhaya',
      registerWithCode: 'Bhalisa ngeKhowudi',
      hospitalDashboard: 'Idashbhodi Yesibhedlele',
      organDonation: 'Ukunikela Ngamalungu',
      leaderboard: 'Ibhodi Yeenkokheli',
      inventory: 'Ibhanki Yegazi',
      predictions: 'Izibonelelo',
      cooldown: 'Umkhondo Wokuphumla',
    },
    home: {
      heroTitle: 'Sidibanisa Abanikeli.',
      heroTitle2: 'Sisindisa Ubomi.',
      heroSubtitle: 'Ukudibanisa ukunikela ngegazi ngexesha lokwenyani eAfrika. Lonke ithontsi libalulekile.',
      registerBtn: 'Bhalisa Njengomnikeli',
      hospitalBtn: 'Ngena Esibhedlele',
      realTimeMatching: 'Ukudibanisa Ngexesha Lokwenyani',
      realTimeDesc: 'Idibanisa ngokukhawuleza abanikeli abahambelanayo nezicelo ezingxamisekileyo ngohlobo lwegazi nendawo',
      urgencyTiers: 'Amanqanaba Okungxama',
      urgencyDesc: 'Amanqanaba eCritical, High, neStandard aqinisekisa ukuba iimeko ezingxamiseke kakhulu zifumana ingqwalasela kuqala',
      verifiedDonors: 'Abanikeli Abaqinisekisiweyo Kuphela',
      verifiedDesc: 'Wonke umnikeli uhlolwa ngokwezonyango kwaye uqinisekiswa esibhedlele ngaphambi kokujoyina iqonga',
      howItWorks: 'Isebenza Njani',
      step1Title: 'Tyelela Isibhedlele',
      step1Desc: 'Yiya kwisibhedlele esithabatha inxaxheba ukuze uhlolwe igazi simahla',
      step2Title: 'Hlolwa',
      step2Desc: 'Uvavanyo lohlobo lwegazi, uvavanyo lwe-BMI, novavanyo lokufaneleka kwempilo',
      step3Title: 'Fumana Ikhowudi',
      step3Desc: 'Xa uvunyelwe, fumana ikhowudi yakho ekhethekileyo yokubhalisa ku-LifeLink',
      step4Title: 'Bhalisa Kwi-intanethi',
      step4Desc: 'Faka ikhowudi yakho ku-LifeLink ukuze uvule iakhawunti yakho yomnikeli',
      statHeadline: 'Rhoqo ngemizuzwana emi-2, kukho umntu odinga igazi.',
      statSubtext: 'EAfrika, igebe phakathi kokuhlinzekwa nesidingo liyabulala kwaye lingathintelwa. I-LifeLink isusa izithintelo.',
      footer: 'LifeLink 2026 — Yakhiwe nge-AWS Serverless Architecture',
    },
    donor: {
      enterCode: 'Faka Ikhowudi Yakho Yokubhalisa',
      codeSubtitle: 'Ufumene le khowudi esibhedlele emva kovavanyo lwakho lwezonyango.',
      registrationCode: 'Ikhowudi Yokubhalisa',
      verifyCode: 'Qinisekisa Ikhowudi',
      noCode: 'Awunayo ikhowudi?',
      noCodeDesc: 'Tyelela isibhedlele sakho esikufutshane esithabatha inxaxheba ukuze uhlolwe ukunikela ngegazi simahla. Xa uvunyelwe, uya kufumana ikhowudi yokubhalisa.',
      codeVerified: 'Ikhowudi Iqinisekisiwe Ngempumelelo',
      contactDetails: 'Iinkcukacha Zoqhagamshelwano',
      phone: 'Inombolo Yefowuni',
      email: 'I-imeyile',
      address: 'Idilesi',
      city: 'Isixeko',
      province: 'Iphondo',
      notificationPrefs: 'Izikhethelo Zezaziso',
      howNotify: 'Kufuneka sikwazise njani?',
      smsOnly: 'I-SMS Kuphela',
      emailOnly: 'I-imeyile Kuphela',
      both: 'Zombini',
      maxDistance: 'Umgama Omde Kakhulu Ozimisele Ukuwuhamba',
      emergencyContact: 'Oqhagamshelwano Lwengxakeko',
      contactName: 'Igama Loqhagamshelwano',
      contactPhone: 'Ifowuni Yoqhagamshelwano',
      completeRegistration: 'Gqibezela Ukubhalisa',
      welcomeTitle: 'Wamkelekile ku-LifeLink!',
      welcomeSubtitle: 'Iakhawunti yakho iyasebenza ngoku. Uya kwaziswa xa isigulana esihambelanayo sikudinga kufutshane.',
      whatNext: 'Kwenzeka ntoni ngokulandelayo?',
      next1: 'Qhubeka nosuku lwakho njengoko uqhele',
      next2: 'Xa isigulana esihambelanayo sidinga igazi kufutshane nawe, uya kufumana isaziso',
      next3: 'Cofa "Ndiza kunikela" ukuqinisekisa, uze uye esibhedlele',
      next4: 'Umhla wakho olandelayo wokufaneleka uya kulandelwa ngokuzenzekelayo (iintsuku ezingama-56 zokuphumla)',
      goHome: 'Yiya Ekhaya',
      viewDemo: 'Jonga Isaziso Sedemo',
    },
    notification: {
      hospitalNeeds: 'idinga',
      blood: 'igazi',
      urgency: 'Ukungxama',
      distance: 'Umgama',
      fromYou: 'ukusuka kuwe',
      illDonate: 'Ndiza Kunikela',
      cantMakeIt: 'Andikwazi',
    },
    common: {
      bloodType: 'Uhlobo Lwegazi',
      units: 'iiyunithi',
      status: 'Imeko',
      active: 'Iyasebenza',
      eligible: 'Iyafaneleka',
      critical: 'Kungxamisekile',
      high: 'Kuphezulu',
      standard: 'Okuqhelekileyo',
      search: 'Khangela',
      filter: 'Hlula',
      cancel: 'Rhoxisa',
      submit: 'Thumela',
      save: 'Gcina',
      back: 'Emva',
      next: 'Okulandelayo',
      loading: 'Iyalayisha...',
      noResults: 'Akukho ziphumo zifunyenweyo',
    },
  },
  st: {
    name: 'Sesotho',
    flag: '🇿🇦',
    nav: {
      home: 'Lehae',
      registerWithCode: 'Ngodisa ka Khoutu',
      hospitalDashboard: 'Dashbhodi ya Sepetlele',
      organDonation: 'Ho Fana ka Ditho',
      leaderboard: 'Lenane la Baetapele',
      inventory: 'Banka ya Mali',
      predictions: 'Diponelopele',
      cooldown: 'Tšhupetso ya Nako ya Phomolo',
    },
    home: {
      heroTitle: 'Re Hokahanya Bafani.',
      heroTitle2: 'Re Pholosa Maphelo.',
      heroSubtitle: 'Ho hokahanya ho fana ka mali nakong ya nnete Afrika. Lerotholi le leng le le leng le bohlokwa.',
      registerBtn: 'Ngodisa Jwalo ka Mofani',
      hospitalBtn: 'Kena Sepetlele',
      realTimeMatching: 'Ho Hokahanya ka Nako ya Nnete',
      realTimeDesc: 'E hokahanya kapele bafani ba tshwanelehang le dikopo tse potlakileng ho latela mofuta wa mali le sebaka',
      urgencyTiers: 'Maemo a Potlako',
      urgencyDesc: 'Maemo a Critical, High, le Standard a netefatsa hore maemo a potlakileng haholo a fumana tlhokomelo pele',
      verifiedDonors: 'Bafani ba Netefaditsweng Feela',
      verifiedDesc: 'Mofani e mong le e mong o hlahlojwa ka bongaka mme o netefatswa sepetlele pele a kena sethala',
      howItWorks: 'E Sebetsa Jwang',
      step1Title: 'Etela Sepetlele',
      step1Desc: 'Eya sepetlele se nkang karolo bakeng sa tlhahlobo ya mali ya mahala',
      step2Title: 'Hlahlojwa',
      step2Desc: 'Tlhahlobo ya mofuta wa mali, tlhahlobo ya BMI, le tlhahlobo ya botsitso ba bophelo',
      step3Title: 'Fumana Khoutu',
      step3Desc: 'Ha o se o dumelletswe, fumana khoutu ya hao e ikgethang ya ho ngodisa ho LifeLink',
      step4Title: 'Ngodisa Inthaneteng',
      step4Desc: 'Kenya khoutu ya hao ho LifeLink ho kenya akhaonto ya hao ya mofani tshebetsong',
      statHeadline: 'Ka metsotswana e 2, ho na le motho ya hlokang mali.',
      statSubtext: 'Afrika, sekgeo pakeng tsa phano le tlhoko se a bolaya mme se ka thibelwa. LifeLink e tlosa mathata.',
      footer: 'LifeLink 2026 — E Hahilwe ka AWS Serverless Architecture',
    },
    donor: {
      enterCode: 'Kenya Khoutu ya Hao ya ho Ngodisa',
      codeSubtitle: 'O fumane khoutu ena sepetlele kamora tlhahlobo ya hao ya bongaka.',
      registrationCode: 'Khoutu ya ho Ngodisa',
      verifyCode: 'Netefatsa Khoutu',
      noCode: 'Ha o na khoutu?',
      noCodeDesc: 'Etela sepetlele sa hao se haufi se nkang karolo bakeng sa tlhahlobo ya ho fana ka mali ya mahala. Ha o se o dumelletswe, o tla fumana khoutu ya ho ngodisa.',
      codeVerified: 'Khoutu e Netefaditswe ka Katleho',
      contactDetails: 'Dintlha tsa Puisano',
      phone: 'Nomoro ya Mohala',
      email: 'Imeile',
      address: 'Aterese',
      city: 'Toropo',
      province: 'Provense',
      notificationPrefs: 'Dikgetho tsa Ditsebiso',
      howNotify: 'Re lokela ho o tsebisa jwang?',
      smsOnly: 'SMS Feela',
      emailOnly: 'Imeile Feela',
      both: 'Ka Bobedi',
      maxDistance: 'Sebaka se Selelele ka ho Fetisisa seo o Ikemiselitseng ho se Tsamaya',
      emergencyContact: 'Motho ya Letswalong la Tshohanyetso',
      contactName: 'Lebitso la Motho',
      contactPhone: 'Mohala wa Motho',
      completeRegistration: 'Phethahatsa ho Ngodisa',
      welcomeTitle: 'O Amohelehile ho LifeLink!',
      welcomeSubtitle: 'Akhaonto ya hao e sebetsa jwale. O tla tsebiswa ha mokudi ya tshwanelehang a o hloka haufi.',
      whatNext: 'Ho etsahala eng ka mor\'a mona?',
      next1: 'Tswela pele ka letsatsi la hao jwalo ka tlwaelo',
      next2: 'Ha mokudi ya tshwanelehang a hloka mali haufi le wena, o tla fumana tsebiso',
      next3: 'Tobetsa "Ke tla Fana" ho netefatsa, ebe o ya sepetlele',
      next4: 'Letsatsi la hao le latelang la ho tshwaneleha le tla latelwa ka bo eona (matsatsi a 56 a phomolo)',
      goHome: 'Eya Hae',
      viewDemo: 'Sheba Tsebiso ya Demo',
    },
    notification: {
      hospitalNeeds: 'e hloka',
      blood: 'mali',
      urgency: 'Potlako',
      distance: 'Sebaka',
      fromYou: 'ho tloha ho wena',
      illDonate: 'Ke tla Fana',
      cantMakeIt: 'Ha ke Kgone',
    },
    common: {
      bloodType: 'Mofuta wa Mali',
      units: 'diyunithi',
      status: 'Boemo',
      active: 'E a Sebetsa',
      eligible: 'E a Tshwaneleha',
      critical: 'E Potlakileng',
      high: 'E Phahameng',
      standard: 'E Tlwaelehileng',
      search: 'Batla',
      filter: 'Sefa',
      cancel: 'Hlakola',
      submit: 'Romela',
      save: 'Boloka',
      back: 'Morao',
      next: 'E Latelang',
      loading: 'E a laela...',
      noResults: 'Ha ho diphetho tse fumaneeng',
    },
  },
  af: {
    name: 'Afrikaans',
    flag: '🇿🇦',
    nav: {
      home: 'Tuis',
      registerWithCode: 'Registreer met Kode',
      hospitalDashboard: 'Hospitaal Kontroleskerm',
      organDonation: 'Orgaanskenking',
      leaderboard: 'Ranglys',
      inventory: 'Bloedbank',
      predictions: 'Voorspellings',
      cooldown: 'Aftydvolger',
    },
    home: {
      heroTitle: 'Verbind Skenkers.',
      heroTitle2: 'Red Lewens.',
      heroSubtitle: 'Intydse bloedskenkingpassing regoor Afrika. Elke druppel tel.',
      registerBtn: 'Registreer as Skenker',
      hospitalBtn: 'Hospitaal Aanmelding',
      realTimeMatching: 'Intydse Passing',
      realTimeDesc: 'Verbind onmiddellik versoenbare skenkers met dringende versoeke gebaseer op bloedtipe en ligging',
      urgencyTiers: 'Dringendheidsvlakke',
      urgencyDesc: 'Kritiese, Hoë en Standaard vlakke verseker dat die dringendste gevalle prioriteit aandag kry',
      verifiedDonors: 'Slegs Geverifieerde Skenkers',
      verifiedDesc: 'Elke skenker word medies ondersoek en geverifieer by \'n hospitaal voordat hulle by die platform aansluit',
      howItWorks: 'Hoe Dit Werk',
      step1Title: 'Besoek Hospitaal',
      step1Desc: 'Gaan na \'n deelnemende hospitaal vir \'n gratis bloedondersoek',
      step2Title: 'Word Ondersoek',
      step2Desc: 'Bloedtipe toets, BMI kontrole, en gesondheidsgeschiktheidsbeoordeling',
      step3Title: 'Ontvang Kode',
      step3Desc: 'Sodra goedgekeur, kry jou unieke LifeLink registrasiekode',
      step4Title: 'Registreer Aanlyn',
      step4Desc: 'Voer jou kode in op LifeLink om jou skenkerrekening te aktiveer',
      statHeadline: 'Elke 2 sekondes het iemand bloed nodig.',
      statSubtext: 'In Afrika is die gaping tussen aanbod en aanvraag dodelik en voorkombaar. LifeLink verwyder die wrywing.',
      footer: 'LifeLink 2026 — Gebou met AWS Bedienerlose Argitektuur',
    },
    donor: {
      enterCode: 'Voer Jou Registrasiekode In',
      codeSubtitle: 'Jy het hierdie kode by die hospitaal ontvang na jou mediese ondersoek.',
      registrationCode: 'Registrasiekode',
      verifyCode: 'Verifieer Kode',
      noCode: 'Het jy nie \'n kode nie?',
      noCodeDesc: 'Besoek jou naaste deelnemende hospitaal vir \'n gratis bloedskenkingondersoek. Sodra goedgekeur, sal jy \'n registrasiekode ontvang.',
      codeVerified: 'Kode Suksesvol Geverifieer',
      contactDetails: 'Kontakbesonderhede',
      phone: 'Telefoonnommer',
      email: 'E-pos',
      address: 'Adres',
      city: 'Stad',
      province: 'Provinsie',
      notificationPrefs: 'Kennisgewingvoorkeure',
      howNotify: 'Hoe moet ons jou in kennis stel?',
      smsOnly: 'Slegs SMS',
      emailOnly: 'Slegs E-pos',
      both: 'Albei',
      maxDistance: 'Maksimum Afstand Bereid om te Reis',
      emergencyContact: 'Noodkontak',
      contactName: 'Kontaknaam',
      contactPhone: 'Kontaktelefoon',
      completeRegistration: 'Voltooi Registrasie',
      welcomeTitle: 'Welkom by LifeLink!',
      welcomeSubtitle: 'Jou rekening is nou aktief. Jy sal in kennis gestel word wanneer \'n versoenbare pasiënt jou naby nodig het.',
      whatNext: 'Wat gebeur volgende?',
      next1: 'Gaan voort met jou dag soos normaal',
      next2: 'Wanneer \'n versoenbare pasiënt bloed naby jou nodig het, sal jy \'n kennisgewing ontvang',
      next3: 'Tik "Ek sal skenk" om te bevestig, gaan dan na die hospitaal',
      next4: 'Jou volgende geskikte skenkingsdatum sal outomaties nagespoor word (56-dae aftyd)',
      goHome: 'Gaan Tuis',
      viewDemo: 'Bekyk Demo Kennisgewing',
    },
    notification: {
      hospitalNeeds: 'benodig',
      blood: 'bloed',
      urgency: 'Dringendheid',
      distance: 'Afstand',
      fromYou: 'van jou af',
      illDonate: 'Ek Sal Skenk',
      cantMakeIt: 'Kan Nie Maak Nie',
    },
    common: {
      bloodType: 'Bloedtipe',
      units: 'eenhede',
      status: 'Status',
      active: 'Aktief',
      eligible: 'Geskik',
      critical: 'Kritiek',
      high: 'Hoog',
      standard: 'Standaard',
      search: 'Soek',
      filter: 'Filter',
      cancel: 'Kanselleer',
      submit: 'Dien In',
      save: 'Stoor',
      back: 'Terug',
      next: 'Volgende',
      loading: 'Laai...',
      noResults: 'Geen resultate gevind nie',
    },
  },
  fr: {
    name: 'Français',
    flag: '🇫🇷',
    nav: {
      home: 'Accueil',
      registerWithCode: "S'inscrire avec Code",
      hospitalDashboard: 'Tableau de Bord Hôpital',
      organDonation: "Don d'Organes",
      leaderboard: 'Classement',
      inventory: 'Banque de Sang',
      predictions: 'Prédictions',
      cooldown: 'Suivi de Repos',
    },
    home: {
      heroTitle: 'Connecter les Donneurs.',
      heroTitle2: 'Sauver des Vies.',
      heroSubtitle: "Mise en relation de dons de sang en temps réel à travers l'Afrique. Chaque goutte compte.",
      registerBtn: "S'inscrire comme Donneur",
      hospitalBtn: 'Connexion Hôpital',
      realTimeMatching: 'Mise en Relation en Temps Réel',
      realTimeDesc: 'Connecte instantanément les donneurs compatibles aux demandes urgentes selon le groupe sanguin et la localisation',
      urgencyTiers: "Niveaux d'Urgence",
      urgencyDesc: "Les niveaux Critique, Élevé et Standard garantissent que les cas les plus urgents reçoivent une attention prioritaire",
      verifiedDonors: 'Donneurs Vérifiés Uniquement',
      verifiedDesc: "Chaque donneur est examiné médicalement et vérifié dans un hôpital avant de rejoindre la plateforme",
      howItWorks: 'Comment Ça Marche',
      step1Title: "Visiter l'Hôpital",
      step1Desc: 'Rendez-vous dans un hôpital participant pour un dépistage sanguin gratuit',
      step2Title: 'Être Examiné',
      step2Desc: "Test de groupe sanguin, contrôle de l'IMC et évaluation d'éligibilité sanitaire",
      step3Title: 'Recevoir le Code',
      step3Desc: "Une fois approuvé, obtenez votre code d'inscription LifeLink unique",
      step4Title: "S'inscrire en Ligne",
      step4Desc: 'Entrez votre code sur LifeLink pour activer votre compte donneur',
      statHeadline: 'Toutes les 2 secondes, quelqu\'un a besoin de sang.',
      statSubtext: "En Afrique, l'écart entre l'offre et la demande est mortel et évitable. LifeLink supprime les obstacles.",
      footer: 'LifeLink 2026 — Construit avec AWS Architecture Serverless',
    },
    donor: {
      enterCode: "Entrez Votre Code d'Inscription",
      codeSubtitle: "Vous avez reçu ce code de l'hôpital après votre examen médical.",
      registrationCode: "Code d'Inscription",
      verifyCode: 'Vérifier le Code',
      noCode: "Vous n'avez pas de code?",
      noCodeDesc: "Visitez votre hôpital participant le plus proche pour un dépistage de don de sang gratuit. Une fois approuvé, vous recevrez un code d'inscription.",
      codeVerified: 'Code Vérifié avec Succès',
      contactDetails: 'Coordonnées',
      phone: 'Numéro de Téléphone',
      email: 'E-mail',
      address: 'Adresse',
      city: 'Ville',
      province: 'Province',
      notificationPrefs: 'Préférences de Notification',
      howNotify: 'Comment devons-nous vous notifier?',
      smsOnly: 'SMS Uniquement',
      emailOnly: 'E-mail Uniquement',
      both: 'Les Deux',
      maxDistance: 'Distance Maximale Prêt à Parcourir',
      emergencyContact: "Contact d'Urgence",
      contactName: 'Nom du Contact',
      contactPhone: 'Téléphone du Contact',
      completeRegistration: "Terminer l'Inscription",
      welcomeTitle: 'Bienvenue sur LifeLink!',
      welcomeSubtitle: "Votre compte est maintenant actif. Vous serez notifié quand un patient compatible a besoin de vous à proximité.",
      whatNext: 'Que se passe-t-il ensuite?',
      next1: 'Continuez votre journée normalement',
      next2: "Quand un patient compatible a besoin de sang près de vous, vous recevrez une notification",
      next3: 'Appuyez sur "Je donne" pour confirmer, puis rendez-vous à l\'hôpital',
      next4: "Votre prochaine date d'éligibilité sera suivie automatiquement (repos de 56 jours)",
      goHome: "Retour à l'Accueil",
      viewDemo: 'Voir la Notification Démo',
    },
    notification: {
      hospitalNeeds: 'a besoin de',
      blood: 'sang',
      urgency: 'Urgence',
      distance: 'Distance',
      fromYou: 'de vous',
      illDonate: 'Je Donne',
      cantMakeIt: 'Je Ne Peux Pas',
    },
    common: {
      bloodType: 'Groupe Sanguin',
      units: 'unités',
      status: 'Statut',
      active: 'Actif',
      eligible: 'Éligible',
      critical: 'Critique',
      high: 'Élevé',
      standard: 'Standard',
      search: 'Rechercher',
      filter: 'Filtrer',
      cancel: 'Annuler',
      submit: 'Soumettre',
      save: 'Enregistrer',
      back: 'Retour',
      next: 'Suivant',
      loading: 'Chargement...',
      noResults: 'Aucun résultat trouvé',
    },
  },
  sw: {
    name: 'Kiswahili',
    flag: '🇰🇪',
    nav: {
      home: 'Nyumbani',
      registerWithCode: 'Jisajili na Msimbo',
      hospitalDashboard: 'Dashibodi ya Hospitali',
      organDonation: 'Uchangiaji wa Viungo',
      leaderboard: 'Ubao wa Viongozi',
      inventory: 'Benki ya Damu',
      predictions: 'Utabiri',
      cooldown: 'Kifuatiliaji cha Mapumziko',
    },
    home: {
      heroTitle: 'Kuunganisha Wafadhili.',
      heroTitle2: 'Kuokoa Maisha.',
      heroSubtitle: 'Kulinganisha uchangiaji wa damu kwa wakati halisi kote Afrika. Kila tone linahesabika.',
      registerBtn: 'Jisajili kama Mfadhili',
      hospitalBtn: 'Ingia Hospitali',
      realTimeMatching: 'Kulinganisha kwa Wakati Halisi',
      realTimeDesc: 'Inaunganisha mara moja wafadhili wanaolingana na maombi ya dharura kulingana na aina ya damu na eneo',
      urgencyTiers: 'Viwango vya Dharura',
      urgencyDesc: 'Viwango vya Muhimu, Juu, na Kawaida vinahakikisha kesi za dharura zaidi zinapata kipaumbele',
      verifiedDonors: 'Wafadhili Waliothibitishwa Pekee',
      verifiedDesc: 'Kila mfadhili anachunguzwa kimatibabu na kuthibitishwa hospitalini kabla ya kujiunga na jukwaa',
      howItWorks: 'Inavyofanya Kazi',
      step1Title: 'Tembelea Hospitali',
      step1Desc: 'Nenda hospitali inayoshiriki kwa uchunguzi wa damu wa bure',
      step2Title: 'Chunguliwa',
      step2Desc: 'Mtihani wa aina ya damu, ukaguzi wa BMI, na tathmini ya ustahiki wa afya',
      step3Title: 'Pokea Msimbo',
      step3Desc: 'Ukishaidhinishwa, pata msimbo wako wa kipekee wa usajili wa LifeLink',
      step4Title: 'Jisajili Mtandaoni',
      step4Desc: 'Ingiza msimbo wako kwenye LifeLink kuamilisha akaunti yako ya mfadhili',
      statHeadline: 'Kila sekunde 2, mtu anahitaji damu.',
      statSubtext: 'Afrika, pengo kati ya ugavi na mahitaji ni hatari na linazuilika. LifeLink inaondoa vikwazo.',
      footer: 'LifeLink 2026 — Imejengwa na AWS Serverless Architecture',
    },
    donor: {
      enterCode: 'Ingiza Msimbo Wako wa Usajili',
      codeSubtitle: 'Ulipokea msimbo huu kutoka hospitalini baada ya uchunguzi wako wa kimatibabu.',
      registrationCode: 'Msimbo wa Usajili',
      verifyCode: 'Thibitisha Msimbo',
      noCode: 'Huna msimbo?',
      noCodeDesc: 'Tembelea hospitali yako ya karibu inayoshiriki kwa uchunguzi wa uchangiaji damu wa bure. Ukishaidhinishwa, utapokea msimbo wa usajili.',
      codeVerified: 'Msimbo Umethibitishwa kwa Mafanikio',
      contactDetails: 'Maelezo ya Mawasiliano',
      phone: 'Nambari ya Simu',
      email: 'Barua pepe',
      address: 'Anwani',
      city: 'Jiji',
      province: 'Mkoa',
      notificationPrefs: 'Mapendeleo ya Arifa',
      howNotify: 'Tukuarifu vipi?',
      smsOnly: 'SMS Pekee',
      emailOnly: 'Barua pepe Pekee',
      both: 'Zote Mbili',
      maxDistance: 'Umbali wa Juu Ulio Tayari Kusafiri',
      emergencyContact: 'Mtu wa Dharura',
      contactName: 'Jina la Mtu',
      contactPhone: 'Simu ya Mtu',
      completeRegistration: 'Kamilisha Usajili',
      welcomeTitle: 'Karibu LifeLink!',
      welcomeSubtitle: 'Akaunti yako iko hai sasa. Utaarifiwa mgonjwa anayelingana anapokuhitaji karibu.',
      whatNext: 'Nini kinafuata?',
      next1: 'Endelea na siku yako kama kawaida',
      next2: 'Mgonjwa anayelingana anapohitaji damu karibu nawe, utapata arifa',
      next3: 'Gonga "Nitachangia" kuthibitisha, kisha nenda hospitalini',
      next4: 'Tarehe yako inayofuata ya kustahiki itafuatiliwa kiotomatiki (siku 56 za mapumziko)',
      goHome: 'Nenda Nyumbani',
      viewDemo: 'Tazama Arifa ya Demo',
    },
    notification: {
      hospitalNeeds: 'inahitaji',
      blood: 'damu',
      urgency: 'Dharura',
      distance: 'Umbali',
      fromYou: 'kutoka kwako',
      illDonate: 'Nitachangia',
      cantMakeIt: 'Siwezi',
    },
    common: {
      bloodType: 'Aina ya Damu',
      units: 'vitengo',
      status: 'Hali',
      active: 'Hai',
      eligible: 'Inastahiki',
      critical: 'Muhimu',
      high: 'Juu',
      standard: 'Kawaida',
      search: 'Tafuta',
      filter: 'Chuja',
      cancel: 'Ghairi',
      submit: 'Wasilisha',
      save: 'Hifadhi',
      back: 'Nyuma',
      next: 'Ifuatayo',
      loading: 'Inapakia...',
      noResults: 'Hakuna matokeo yaliyopatikana',
    },
  },
};

const supportedLanguages = Object.keys(translations);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('lifelink-language') || 'en';
  });

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem('lifelink-language', lang);
  };

  const t = (path) => {
    const keys = path.split('.');
    let result = translations[language];
    for (const key of keys) {
      result = result?.[key];
    }
    return result || translations['en']?.[keys[0]]?.[keys[1]] || path;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t, supportedLanguages, translations }}>
      {children}
    </LanguageContext.Provider>
  );
}

